/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.CtlBancoPreguntas;
import controladores.CtlCrearEncuesta;
import controladores.CtlCrearPreguntas;
import excepciones.ConexionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author SEBASTIAN
 */
public class FrmCrearPreguntas extends JInternalFrame {

    /**
     * Creates new form FrmCrearPreguntas
     */
    int idSubcategoria;
    int idCategoria;
    CtlCrearEncuesta controlador;
    CtlCrearPreguntas controladorPregunta;
    private JFrame ventanaActual;
    FrmEleccionUnica eleccionUnica;

    public FrmCrearPreguntas() {
        initComponents();
        controlador = new CtlCrearEncuesta();
        controladorPregunta = new CtlCrearPreguntas();
        try {
            cargarCategorias();
            tblLista.setModel(controladorPregunta.ListadoPregunta(tblLista));
        } catch (ConexionException ex) {
            Logger.getLogger(FrmCrearPreguntas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        cmbSupCategoria = new javax.swing.JComboBox<>();
        btnSeleccionarPregunta = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1365, 670));
        setMinimumSize(new java.awt.Dimension(1365, 670));
        setPreferredSize(new java.awt.Dimension(1365, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 113, 193));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/pregunta.png"))); // NOI18N
        jLabel2.setText("Crear Preguntas");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 260, 60));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 190, 10));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 120));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 113, 193));
        jLabel3.setText("CATEGORIA :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 113, 193));
        jLabel4.setText("SUBCATEGORIA:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        cmbCategoria.setBackground(new java.awt.Color(255, 255, 255));
        cmbCategoria.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        cmbCategoria.setForeground(new java.awt.Color(0, 0, 0));
        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });
        jPanel3.add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 180, 30));

        cmbSupCategoria.setBackground(new java.awt.Color(255, 255, 255));
        cmbSupCategoria.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        cmbSupCategoria.setForeground(new java.awt.Color(0, 0, 0));
        cmbSupCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        jPanel3.add(cmbSupCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 180, 30));

        btnSeleccionarPregunta.setBackground(new java.awt.Color(0, 51, 102));
        btnSeleccionarPregunta.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        btnSeleccionarPregunta.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarPregunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/selec.png"))); // NOI18N
        btnSeleccionarPregunta.setText("Seleccionar Tipo De Pregunta");
        btnSeleccionarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarPreguntaActionPerformed(evt);
            }
        });
        jPanel3.add(btnSeleccionarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 610, 320));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblLista.setForeground(new java.awt.Color(0, 0, 0));
        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLista.setGridColor(new java.awt.Color(0, 0, 0));
        tblLista.setSelectionBackground(new java.awt.Color(0, 113, 193));
        tblLista.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblLista);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 690, 450));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 710, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 670));

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarPreguntaActionPerformed
        // TODO add your handling code here:
        int idSubcategoria = controlador.getListaSubcategorias().get(cmbSupCategoria.getSelectedIndex()).getId();
        FrmPreguntas frm = new FrmPreguntas(idSubcategoria);
        frm.setVisible(true);

    }//GEN-LAST:event_btnSeleccionarPreguntaActionPerformed

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        try {
            idCategoria = controlador.getListaCategorias().get(cmbCategoria.getSelectedIndex()).getId();
            cmbSupCategoria.removeAllItems();
            for (int i = 0; i < controlador.obtenerSubcategorias(idCategoria).size(); i++) {
                cmbSupCategoria.addItem(controlador.obtenerSubcategorias(idCategoria).get(i).getNombre());
            }
        } catch (NullPointerException ex) {

        } catch (ConexionException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    public void cargarCategorias() {
        try {
            cmbCategoria.removeAllItems();
            for (int i = 0; i < controlador.obtenerCategorias().size(); i++) {
                cmbCategoria.addItem(controlador.obtenerCategorias().get(i).getNombre());
            }
        } catch (ConexionException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCrearPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCrearPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCrearPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCrearPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCrearPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionarPregunta;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbSupCategoria;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblLista;
    // End of variables declaration//GEN-END:variables

}
