/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.CtlCrearPreguntas;
import excepciones.ConexionException;
import excepciones.DniUnicoExcepcion;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import modelo.Opcion;

/**
 *
 * @author nicolasdurangarces
 */
public class FrmEleccionEscala extends JInternalFrame {

    /**
     * Creates new form FrmEscalaNumerica
     */
    CtlCrearPreguntas controladorAgrePreguntas;
    int idSupCategoria;
    int x;

    public FrmEleccionEscala() {
        initComponents();
        setVisible(true);
        setMaximizable(false);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        panelNominal.setVisible(false);
        panelNumerico.setVisible(false);
    }

    public FrmEleccionEscala(int idSubCategoria) {
        initComponents();
        setVisible(true);
        setMaximizable(false);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.idSupCategoria = idSubCategoria;
        panelNominal.setVisible(false);
        panelNumerico.setVisible(false);
        controladorAgrePreguntas = new CtlCrearPreguntas();
        x = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtgTipoSeleccion = new javax.swing.ButtonGroup();
        BtgPreguntas = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        RdbNumerico = new javax.swing.JRadioButton();
        RdbNominal = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtEnunciado = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        panelNumerico = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        txtOpcionNumerica = new javax.swing.JTextField();
        txtRes1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNumerica = new javax.swing.JTable();
        panelNominal = new javax.swing.JPanel();
        RdbSeleccionSi = new javax.swing.JRadioButton();
        txtOpcionNominal = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNominal = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        pnlSumar = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JToggleButton();
        btnEliminar = new javax.swing.JButton();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(640, 510));
        setMinimumSize(new java.awt.Dimension(640, 510));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(640, 510));

        jPanel1.setMaximumSize(new java.awt.Dimension(640, 440));
        jPanel1.setMinimumSize(new java.awt.Dimension(640, 440));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 440));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 113, 193));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 113, 193));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Tipo De Seleccion Única", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai Light", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Dubai Light", 0, 12)); // NOI18N

        RdbNumerico.setBackground(new java.awt.Color(0, 113, 193));
        BtgTipoSeleccion.add(RdbNumerico);
        RdbNumerico.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        RdbNumerico.setForeground(new java.awt.Color(255, 255, 255));
        RdbNumerico.setText("Numerica");
        RdbNumerico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RdbNumericoMouseClicked(evt);
            }
        });
        RdbNumerico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdbNumericoActionPerformed(evt);
            }
        });

        RdbNominal.setBackground(new java.awt.Color(0, 113, 193));
        BtgTipoSeleccion.add(RdbNominal);
        RdbNominal.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        RdbNominal.setForeground(new java.awt.Color(255, 255, 255));
        RdbNominal.setText("Nominal");
        RdbNominal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RdbNominalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(RdbNumerico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RdbNominal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RdbNumerico)
                    .addComponent(RdbNominal))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 240, 70));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ENUNCIADO DE LA PREGUNTA:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txtEnunciado.setBackground(new java.awt.Color(0, 113, 193));
        txtEnunciado.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtEnunciado.setForeground(new java.awt.Color(0, 0, 0));
        txtEnunciado.setBorder(null);
        txtEnunciado.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtEnunciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 600, 20));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 600, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 180));

        panelNumerico.setBackground(new java.awt.Color(255, 255, 255));
        panelNumerico.setMaximumSize(new java.awt.Dimension(642, 231));
        panelNumerico.setMinimumSize(new java.awt.Dimension(642, 231));
        panelNumerico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(0, 113, 193));
        jSeparator2.setForeground(new java.awt.Color(0, 113, 193));
        panelNumerico.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 475, 10));

        txtOpcionNumerica.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtOpcionNumerica.setForeground(new java.awt.Color(0, 0, 0));
        txtOpcionNumerica.setBorder(null);
        panelNumerico.add(txtOpcionNumerica, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 475, 20));

        txtRes1.setEnabled(false);
        panelNumerico.add(txtRes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 35, -1));

        tblNumerica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblNumerica);

        panelNumerico.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 570, 169));

        jPanel1.add(panelNumerico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 580, 231));

        panelNominal.setBackground(new java.awt.Color(255, 255, 255));
        panelNominal.setMaximumSize(new java.awt.Dimension(642, 231));
        panelNominal.setMinimumSize(new java.awt.Dimension(642, 231));
        panelNominal.setPreferredSize(new java.awt.Dimension(642, 231));
        panelNominal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RdbSeleccionSi.setBackground(new java.awt.Color(255, 255, 255));
        BtgPreguntas.add(RdbSeleccionSi);
        RdbSeleccionSi.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        RdbSeleccionSi.setForeground(new java.awt.Color(0, 102, 102));
        panelNominal.add(RdbSeleccionSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        txtOpcionNominal.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtOpcionNominal.setForeground(new java.awt.Color(0, 0, 0));
        txtOpcionNominal.setBorder(null);
        panelNominal.add(txtOpcionNominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 400, 20));

        jSeparator7.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator7.setForeground(new java.awt.Color(0, 102, 102));
        panelNominal.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 400, 10));

        tblNominal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblNominal);

        panelNominal.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 540, 160));

        jPanel1.add(panelNominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 580, 231));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setBackground(new java.awt.Color(0, 51, 102));
        btnGuardar.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/guardar.png"))); // NOI18N
        btnGuardar.setText("GUADAR");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), null, null));
        btnGuardar.setBorderPainted(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel4.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 130, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 640, 80));

        pnlSumar.setBackground(new java.awt.Color(255, 255, 255));

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/agregar-pregunta.png"))); // NOI18N
        btnAgregar.setBorder(null);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/quitar-pregunta.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSumarLayout = new javax.swing.GroupLayout(pnlSumar);
        pnlSumar.setLayout(pnlSumarLayout);
        pnlSumarLayout.setHorizontalGroup(
            pnlSumarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSumarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSumarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addContainerGap())
        );
        pnlSumarLayout.setVerticalGroup(
            pnlSumarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSumarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jPanel1.add(pnlSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RdbNumericoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdbNumericoMouseClicked
        // Abrimor el panel si es Dicotomica
        if (panelNominal.isEnabled()) {
            panelNominal.setVisible(false);
            panelNumerico.setVisible(true);
            Limpiar();
        } else {
            panelNumerico.setVisible(true);
        }
    }//GEN-LAST:event_RdbNumericoMouseClicked

    private void RdbNominalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdbNominalMouseClicked
        // Abrimor el panel si es Dicotomica
        if (panelNumerico.isEnabled()) {
            panelNumerico.setVisible(false);
            panelNominal.setVisible(true);
            Limpiar();
        } else {
            panelNominal.setVisible(true);
        }
    }//GEN-LAST:event_RdbNominalMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int tipoPregunta;
        String enunciado = txtEnunciado.getText();
        if (RdbNumerico.isSelected()) {
            if (enunciado.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Debe Agregar Opciones");
            } else {
                tipoPregunta = 7;
                try {
                    if (controladorAgrePreguntas.crear(tipoPregunta, idSupCategoria, enunciado, false)) {
                        JOptionPane.showMessageDialog(null, "Registro Exitoso");
                        Limpiar();
                        this.dispose();
                    }
                } catch (DniUnicoExcepcion | ConexionException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }
        } else if (RdbNominal.isSelected()) {
            if (enunciado.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Debe Agregar Opciones");
            } else {
                tipoPregunta = 8;
                try {
                    if (controladorAgrePreguntas.crear(tipoPregunta, idSupCategoria, enunciado, false)) {
                        JOptionPane.showMessageDialog(null, "Registro Exitoso");
                        Limpiar();
                        this.dispose();
                    }
                } catch (DniUnicoExcepcion | ConexionException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por Favor Elija Su Tipo De Pregunta");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (RdbNumerico.isSelected()) {
            if (txtEnunciado.getText().isEmpty() || txtOpcionNumerica.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Todos los campos son requeridos");
            } else {
                Opcion op = new Opcion(0, x + 1, txtOpcionNumerica.getText(), false);
                txtOpcionNumerica.setText("");
                tblNumerica.setModel(controladorAgrePreguntas.cargarTabla(op, tblNumerica));
                x++;
            }
        } else if (RdbNominal.isSelected()) {
            if (txtEnunciado.getText().isEmpty() || txtOpcionNominal.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Todos los campos son requeridos");
            } else {
                Opcion op = new Opcion(0, x + 1, txtOpcionNominal.getText(), false);
                txtOpcionNominal.setText("");
                tblNominal.setModel(controladorAgrePreguntas.cargarTabla(op, tblNominal));
                x++;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por Favor Elija Su Tipo De Pregunta");
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void RdbNumericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdbNumericoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdbNumericoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int indice = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el Id de la opcion que desea Eliminar"));
        controladorAgrePreguntas.eliminarOpcion(indice);
        if (RdbNumerico.isSelected()) {
            tblNumerica.setModel(controladorAgrePreguntas.cargarTabla(null, tblNumerica));
        } else if (RdbNominal.isSelected()) {
            tblNominal.setModel(controladorAgrePreguntas.cargarTabla(null, tblNominal));
        }
        JOptionPane.showMessageDialog(null, "Opcion Descartada");
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEleccionEscala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEleccionEscala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEleccionEscala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEleccionEscala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEleccionEscala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtgPreguntas;
    private javax.swing.ButtonGroup BtgTipoSeleccion;
    private javax.swing.JRadioButton RdbNominal;
    private javax.swing.JRadioButton RdbNumerico;
    private javax.swing.JRadioButton RdbSeleccionSi;
    private javax.swing.JToggleButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel panelNominal;
    private javax.swing.JPanel panelNumerico;
    private javax.swing.JPanel pnlSumar;
    private javax.swing.JTable tblNominal;
    private javax.swing.JTable tblNumerica;
    private javax.swing.JTextField txtEnunciado;
    private javax.swing.JTextField txtOpcionNominal;
    private javax.swing.JTextField txtOpcionNumerica;
    private javax.swing.JTextField txtRes1;
    // End of variables declaration//GEN-END:variables

    private void Limpiar() {
        txtEnunciado.setText("");
        txtOpcionNumerica.setText("");
        txtOpcionNominal.setText("");
        controladorAgrePreguntas.limpiarArray();
        x = 0;
    }
}
