/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.CtlCrearPreguntas;
import excepciones.ConexionException;
import excepciones.DniUnicoExcepcion;
import javax.swing.JOptionPane;
import modelo.Opcion;

/**
 *
 * @author nicolasdurangarces
 */
public class FrmEleccionMultiple extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmEleccionUnicaDicotomicas
     */
    CtlCrearPreguntas controladorAgrePreguntas;
    int idSupCategoria;
    int x;

    public FrmEleccionMultiple() {
        initComponents();
        setVisible(true);
        setMaximizable(false);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    FrmEleccionMultiple(int idSupCategoria) {
        initComponents();
        setVisible(true);
        setMaximizable(false);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.idSupCategoria = idSupCategoria;
        controladorAgrePreguntas = new CtlCrearPreguntas();
        x = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CbxSeleccion1 = new javax.swing.JCheckBox();
        txtOpcionMultiple = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnRegistrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        txtEnunciado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMultiple = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(640, 440));
        setMinimumSize(new java.awt.Dimension(640, 440));
        setPreferredSize(new java.awt.Dimension(640, 440));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CbxSeleccion1.setBackground(new java.awt.Color(255, 255, 255));
        CbxSeleccion1.setForeground(new java.awt.Color(0, 0, 0));
        CbxSeleccion1.setEnabled(false);
        jPanel1.add(CbxSeleccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        txtOpcionMultiple.setBorder(null);
        jPanel1.add(txtOpcionMultiple, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 500, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 113, 193));
        jSeparator2.setForeground(new java.awt.Color(0, 113, 193));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 500, 10));

        btnRegistrar.setBackground(new java.awt.Color(0, 51, 102));
        btnRegistrar.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/guardar.png"))); // NOI18N
        btnRegistrar.setText("GUADAR");
        btnRegistrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), null, null));
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 130, -1));

        jPanel2.setBackground(new java.awt.Color(0, 113, 193));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 59, 600, 20));

        txtEnunciado.setBackground(new java.awt.Color(0, 113, 193));
        txtEnunciado.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        txtEnunciado.setForeground(new java.awt.Color(0, 0, 0));
        txtEnunciado.setBorder(null);
        txtEnunciado.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtEnunciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 31, 600, -1));

        jLabel1.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ENUNCIADO DE LA PREGUNTA:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 90));

        tblMultiple.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMultiple);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 540, 190));

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/agregar-pregunta.png"))); // NOI18N
        btnAgregar.setBorder(null);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 30, 30));

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/quitar-pregunta.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        int tipoPregunta = 4;
        String enunciado = txtEnunciado.getText();

        if (enunciado.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los campos son requeridos");
        } else {
            try {
                if (controladorAgrePreguntas.crear(tipoPregunta, idSupCategoria, enunciado, false)) {
                    JOptionPane.showMessageDialog(null, "Registro Exitoso");
                    Limpiar();
                    this.dispose();
                }
            } catch (DniUnicoExcepcion | ConexionException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (txtEnunciado.getText().isEmpty() || txtOpcionMultiple.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los campos son requeridos");
        } else {
            Opcion op = new Opcion(0, x + 1, txtOpcionMultiple.getText(), false);
            txtOpcionMultiple.setText("");
            tblMultiple.setModel(controladorAgrePreguntas.cargarTabla(op, tblMultiple));
            x++;
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int indice = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el Id de la opcion que desea Eliminar"));
        controladorAgrePreguntas.eliminarOpcion(indice);
        tblMultiple.setModel(controladorAgrePreguntas.cargarTabla(null, tblMultiple));
        JOptionPane.showMessageDialog(null, "Opcion Descartada");
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEleccionMultiple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEleccionMultiple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEleccionMultiple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEleccionMultiple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEleccionMultiple().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CbxSeleccion1;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable tblMultiple;
    private javax.swing.JTextField txtEnunciado;
    private javax.swing.JTextField txtOpcionMultiple;
    // End of variables declaration//GEN-END:variables
    private void Limpiar() {
        txtEnunciado.setText("");
        txtOpcionMultiple.setText("");
        controladorAgrePreguntas.limpiarArray();
        x = 0;
    }
}
