/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.CtlElegirEncuesta;
import excepciones.ConexionException;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import modelo.Encuesta;

/**
 *
 * @author jose
 */
public class FrmElegirEncuesta extends javax.swing.JInternalFrame {

    int idSubcategoria;
    int idCategoria;
    Encuesta encuesta;
    CtlElegirEncuesta controlador;

    /**
     * Creates new form FrmElegirEncuesta
     */
    public FrmElegirEncuesta() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        setVisible(true);
        setMaximizable(false);
        controlador = new CtlElegirEncuesta();
        cargarCategorias();
        try {
            controlador.cargarEncuestasPublicas();
            tblEncuestas.setModel(controlador.listarEncuestas());
        } catch (ConexionException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbCategoria = new javax.swing.JComboBox<>();
        cmbSubcategoria = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbVisibilidad = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEncuestas = new javax.swing.JTable();
        btnPresentar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmbCategoria.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });

        cmbSubcategoria.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        cmbSubcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSubcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSubcategoriaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 113, 193));
        jLabel11.setText("Categoria");

        jLabel12.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 113, 193));
        jLabel12.setText("SubCategoria");

        cmbVisibilidad.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        cmbVisibilidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Públicos", "Privados" }));
        cmbVisibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVisibilidadActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 113, 193));
        jLabel13.setText("Visibilidad");

        tblEncuestas.setAutoCreateRowSorter(true);
        tblEncuestas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEncuestas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tblEncuestas.setGridColor(new java.awt.Color(0, 0, 0));
        tblEncuestas.setSelectionBackground(new java.awt.Color(0, 113, 193));
        tblEncuestas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEncuestasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEncuestas);

        btnPresentar.setBackground(new java.awt.Color(0, 51, 102));
        btnPresentar.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        btnPresentar.setForeground(new java.awt.Color(255, 255, 255));
        btnPresentar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/log.png"))); // NOI18N
        btnPresentar.setText("Presentar Encuesta");
        btnPresentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresentarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(27, 27, 27)
                        .addComponent(cmbVisibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(jLabel11)
                        .addGap(30, 30, 30)
                        .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143)
                        .addComponent(jLabel12)
                        .addGap(27, 27, 27)
                        .addComponent(cmbSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(btnPresentar)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbSubcategoria)
                                .addComponent(cmbVisibilidad)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(btnPresentar)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        try {
            idCategoria = controlador.getListaCategorias().get(cmbCategoria.getSelectedIndex()).getId();
            cmbSubcategoria.removeAllItems();
            for (int i = 0; i < controlador.obtenerSubcategorias(idCategoria).size(); i++) {
                cmbSubcategoria.addItem(controlador.obtenerSubcategorias(idCategoria).get(i).getNombre());
            }
        } catch (NullPointerException ex) {

        } catch (ConexionException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void cmbSubcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSubcategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSubcategoriaActionPerformed

    private void cmbVisibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVisibilidadActionPerformed

        String tipo = cmbVisibilidad.getSelectedItem().toString();
        try {
            
            if (tipo.equals("Privados")) {
                
                controlador.cargarEncuestasPrivadas(FrmLogin.userID);
                tblEncuestas.setModel(controlador.listarEncuestas());
            } else {
                controlador.cargarEncuestasPublicas();
                
                tblEncuestas.setModel(controlador.listarEncuestas());
            }
        } catch (ConexionException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_cmbVisibilidadActionPerformed

    private void tblEncuestasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEncuestasMouseClicked
        int pos = tblEncuestas.getSelectedRow();

        if (pos >= 0) {
            encuesta = controlador.cargarEncuestaSeleccionada(pos);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un registro");
        }
    }//GEN-LAST:event_tblEncuestasMouseClicked

    private void btnPresentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresentarActionPerformed

        FrmPresentarEncuesta presentarEncuesta = new FrmPresentarEncuesta(FrmLogin.userID, encuesta.getId());
        presentarEncuesta.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnPresentarActionPerformed

    public void cargarCategorias() {
        try {
            cmbCategoria.removeAllItems();
            for (int i = 0; i < controlador.obtenerCategorias().size(); i++) {
                cmbCategoria.addItem(controlador.obtenerCategorias().get(i).getNombre());
            }
        } catch (ConexionException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmElegirEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmElegirEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmElegirEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmElegirEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmElegirEncuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPresentar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbSubcategoria;
    private javax.swing.JComboBox<String> cmbVisibilidad;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEncuestas;
    // End of variables declaration//GEN-END:variables
}
