/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.CtlCrearPreguntas;
import excepciones.ConexionException;
import excepciones.DniUnicoExcepcion;
import javax.swing.JOptionPane;
import modelo.Opcion;

/**
 *
 * @author nicolasdurangarces
 */
public class FrmEleccionUnica extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmEleccionUnicaDicotomicas
     */
    CtlCrearPreguntas controladorAgrePreguntas;
    int idSupCategoria;
    int x;

    public FrmEleccionUnica() {
        initComponents();
        setVisible(true);
        setMaximizable(false);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        PnlSeleccionDicotomica.setVisible(false);
        PnlSeleccionPolitomica.setVisible(false);
    }

    FrmEleccionUnica(int idSupCategoria) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        setVisible(true);
        setMaximizable(false);
        this.idSupCategoria = idSupCategoria;
        PnlSeleccionDicotomica.setVisible(false);
        PnlSeleccionPolitomica.setVisible(false);
        controladorAgrePreguntas = new CtlCrearPreguntas();
        x = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtgTipoSeleccionUnica = new javax.swing.ButtonGroup();
        BtgSeleccionRespuestaDicotomica = new javax.swing.ButtonGroup();
        BtgSeleccionRespuestaPolitomica = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        RdbDicotomicas = new javax.swing.JRadioButton();
        RdbPolitomicas = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtEnunciado = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        PnlSeleccionDicotomica = new javax.swing.JPanel();
        txtOpcionDicotomica = new javax.swing.JTextField();
        RdbSeleccionSi = new javax.swing.JRadioButton();
        jSeparator7 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDicotomicas = new javax.swing.JTable();
        PnlSeleccionPolitomica = new javax.swing.JPanel();
        RdbSeleccion1 = new javax.swing.JRadioButton();
        txtOpcionPolitomica = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPolitomica = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(640, 510));
        setMinimumSize(new java.awt.Dimension(640, 510));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(640, 510));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(640, 440));
        jPanel1.setMinimumSize(new java.awt.Dimension(640, 440));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 440));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 113, 193));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 113, 193));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Tipo De Seleccion Única", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Dubai Light", 0, 12)); // NOI18N

        RdbDicotomicas.setBackground(new java.awt.Color(0, 113, 193));
        BtgTipoSeleccionUnica.add(RdbDicotomicas);
        RdbDicotomicas.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        RdbDicotomicas.setForeground(new java.awt.Color(255, 255, 255));
        RdbDicotomicas.setText("Dicotómicas");
        RdbDicotomicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RdbDicotomicasMouseClicked(evt);
            }
        });

        RdbPolitomicas.setBackground(new java.awt.Color(0, 113, 193));
        BtgTipoSeleccionUnica.add(RdbPolitomicas);
        RdbPolitomicas.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        RdbPolitomicas.setForeground(new java.awt.Color(255, 255, 255));
        RdbPolitomicas.setText("Politómicas");
        RdbPolitomicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RdbPolitomicasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RdbDicotomicas)
                .addGap(18, 18, 18)
                .addComponent(RdbPolitomicas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RdbDicotomicas)
                    .addComponent(RdbPolitomicas))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 240, 70));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ENUNCIADO DE LA PREGUNTA:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txtEnunciado.setBackground(new java.awt.Color(0, 113, 193));
        txtEnunciado.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        txtEnunciado.setForeground(new java.awt.Color(0, 0, 0));
        txtEnunciado.setBorder(null);
        jPanel2.add(txtEnunciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 600, 20));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 600, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 140));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlSeleccionDicotomica.setBackground(new java.awt.Color(255, 255, 255));

        txtOpcionDicotomica.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtOpcionDicotomica.setForeground(new java.awt.Color(0, 0, 0));
        txtOpcionDicotomica.setBorder(null);

        RdbSeleccionSi.setBackground(new java.awt.Color(255, 255, 255));
        RdbSeleccionSi.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        RdbSeleccionSi.setForeground(new java.awt.Color(0, 102, 102));
        RdbSeleccionSi.setEnabled(false);

        jSeparator7.setBackground(new java.awt.Color(0, 113, 193));
        jSeparator7.setForeground(new java.awt.Color(0, 113, 193));

        tblDicotomicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDicotomicas);

        javax.swing.GroupLayout PnlSeleccionDicotomicaLayout = new javax.swing.GroupLayout(PnlSeleccionDicotomica);
        PnlSeleccionDicotomica.setLayout(PnlSeleccionDicotomicaLayout);
        PnlSeleccionDicotomicaLayout.setHorizontalGroup(
            PnlSeleccionDicotomicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlSeleccionDicotomicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RdbSeleccionSi)
                .addGap(9, 9, 9)
                .addGroup(PnlSeleccionDicotomicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOpcionDicotomica, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PnlSeleccionDicotomicaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );
        PnlSeleccionDicotomicaLayout.setVerticalGroup(
            PnlSeleccionDicotomicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlSeleccionDicotomicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlSeleccionDicotomicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RdbSeleccionSi)
                    .addGroup(PnlSeleccionDicotomicaLayout.createSequentialGroup()
                        .addComponent(txtOpcionDicotomica, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(PnlSeleccionDicotomica, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, -2, 570, 280));

        PnlSeleccionPolitomica.setBackground(new java.awt.Color(255, 255, 255));
        PnlSeleccionPolitomica.setMaximumSize(new java.awt.Dimension(570, 280));
        PnlSeleccionPolitomica.setMinimumSize(new java.awt.Dimension(570, 280));
        PnlSeleccionPolitomica.setPreferredSize(new java.awt.Dimension(570, 280));
        PnlSeleccionPolitomica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RdbSeleccion1.setBackground(new java.awt.Color(255, 255, 255));
        BtgSeleccionRespuestaPolitomica.add(RdbSeleccion1);
        RdbSeleccion1.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        RdbSeleccion1.setForeground(new java.awt.Color(0, 0, 0));
        PnlSeleccionPolitomica.add(RdbSeleccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txtOpcionPolitomica.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        txtOpcionPolitomica.setForeground(new java.awt.Color(0, 0, 0));
        txtOpcionPolitomica.setBorder(null);
        PnlSeleccionPolitomica.add(txtOpcionPolitomica, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 494, 20));

        jSeparator3.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        PnlSeleccionPolitomica.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 500, 10));

        tblPolitomica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPolitomica);

        PnlSeleccionPolitomica.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 520, 200));

        jPanel4.add(PnlSeleccionPolitomica, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -2, 580, 280));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 580, 280));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btnRegistrar.setBackground(new java.awt.Color(0, 51, 102));
        btnRegistrar.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/guardar.png"))); // NOI18N
        btnRegistrar.setText("GUADAR");
        btnRegistrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), null, null));
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(499, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistrar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 650, 70));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/agregar-pregunta.png"))); // NOI18N
        btnAgregar.setBorder(null);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/quitar-pregunta.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminar)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 70, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RdbDicotomicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdbDicotomicasMouseClicked
        // Abrimor el panel si es Dicotomica
        if (PnlSeleccionPolitomica.isEnabled()) {
            PnlSeleccionPolitomica.setVisible(false);
            PnlSeleccionDicotomica.setVisible(true);
            Limpiar();
        } else {
            PnlSeleccionDicotomica.setVisible(true);
            Limpiar();
        }

    }//GEN-LAST:event_RdbDicotomicasMouseClicked

    private void RdbPolitomicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdbPolitomicasMouseClicked
        // Abrimor el panel si es Dicotomica
        if (PnlSeleccionDicotomica.isEnabled()) {
            PnlSeleccionDicotomica.setVisible(false);
            PnlSeleccionPolitomica.setVisible(true);
            Limpiar();
        } else {
            PnlSeleccionPolitomica.setVisible(true);
            Limpiar();
        }
    }//GEN-LAST:event_RdbPolitomicasMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        int tipoPregunta;
        String enunciado = txtEnunciado.getText();
        if (RdbDicotomicas.isSelected()) {
            if (enunciado.isEmpty() ) {
                JOptionPane.showMessageDialog(null, "Debe Agregar Opciones");
            } else {
                tipoPregunta = 2;
                try {
                    if (controladorAgrePreguntas.crear(tipoPregunta, idSupCategoria, enunciado, false)) {
                        JOptionPane.showMessageDialog(null, "Registro Exitoso");
                        Limpiar();
                        this.dispose();
                    }
                } catch (DniUnicoExcepcion | ConexionException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }
        } else if (RdbPolitomicas.isSelected()) {
            if (enunciado.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Todos los campos son requeridos");
            } else {
                tipoPregunta = 3;
                try {
                    if (controladorAgrePreguntas.crear(tipoPregunta, idSupCategoria, enunciado, false)) {
                        JOptionPane.showMessageDialog(null, "Registro Exitoso");
                        Limpiar();
                        this.dispose();
                    }
                } catch (DniUnicoExcepcion | ConexionException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por Favor Elija Su Tipo De Pregunta");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (RdbDicotomicas.isSelected()) {
            if (txtEnunciado.getText().isEmpty() || txtOpcionDicotomica.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Todos los campos son requeridos");
            } else {
                Opcion op = new Opcion(0, x + 1, txtOpcionDicotomica.getText(), false);
                tblDicotomicas.setModel(controladorAgrePreguntas.cargarTabla(op, tblDicotomicas));
                txtOpcionDicotomica.setText("");
                x++;
            }
        } else if (RdbPolitomicas.isSelected()) {
            if (txtEnunciado.getText().isEmpty() || txtOpcionPolitomica.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Todos los campos son requeridos");
            } else {
                Opcion op = new Opcion(0, x + 1, txtOpcionPolitomica.getText(), false);
                tblPolitomica.setModel(controladorAgrePreguntas.cargarTabla(op, tblPolitomica));
                txtOpcionPolitomica.setText("");
                x++;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por Favor Elija Su Tipo De Pregunta");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int indice = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el Id de la opcion que desea Eliminar"));
        controladorAgrePreguntas.eliminarOpcion(indice);
        if (RdbDicotomicas.isSelected()) {
            tblDicotomicas.setModel(controladorAgrePreguntas.cargarTabla(null, tblDicotomicas));
        } else if (RdbPolitomicas.isSelected()) {
            tblPolitomica.setModel(controladorAgrePreguntas.cargarTabla(null, tblPolitomica));
        }
        JOptionPane.showMessageDialog(null, "Opcion Descartada");
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEleccionUnica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEleccionUnica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEleccionUnica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEleccionUnica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new FrmEleccionUnica().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtgSeleccionRespuestaDicotomica;
    private javax.swing.ButtonGroup BtgSeleccionRespuestaPolitomica;
    private javax.swing.ButtonGroup BtgTipoSeleccionUnica;
    private javax.swing.JPanel PnlSeleccionDicotomica;
    private javax.swing.JPanel PnlSeleccionPolitomica;
    private javax.swing.JRadioButton RdbDicotomicas;
    private javax.swing.JRadioButton RdbPolitomicas;
    private javax.swing.JRadioButton RdbSeleccion1;
    private javax.swing.JRadioButton RdbSeleccionSi;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable tblDicotomicas;
    private javax.swing.JTable tblPolitomica;
    private javax.swing.JTextField txtEnunciado;
    private javax.swing.JTextField txtOpcionDicotomica;
    private javax.swing.JTextField txtOpcionPolitomica;
    // End of variables declaration//GEN-END:variables
 private void Limpiar() {
        txtEnunciado.setText("");
        txtOpcionDicotomica.setText("");
        txtOpcionPolitomica.setText("");
        controladorAgrePreguntas.limpiarArray();
        x = 0;
    }
}
