/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import vistas.MenuPrincipal;
import controladores.CtlLogIn;
import excepciones.ConexionException;
import excepciones.PasswordIncorrectoException;
import excepciones.UsernameIncorrectoException;
import javax.swing.JOptionPane;
import modelo.Login;

/**
 *
 * @author niduga
 */
public class FrmLogin extends javax.swing.JFrame {

    public static String role;
    public static Long userID;
    CtlLogIn controlador;

    /**
     * Creates new form Login
     */
    public FrmLogin() {
        initComponents();
        controlador = new CtlLogIn();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        boton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        psfPassword = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        btnIniciarSesion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(900, 630));
        setMinimumSize(new java.awt.Dimension(900, 630));
        setSize(new java.awt.Dimension(900, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 113, 193));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/web.png"))); // NOI18N
        jLabel1.setText("LOGIN_");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 230, 70));

        jLabel2.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 113, 193));
        jLabel2.setText("Usuario :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 113, 193));
        jLabel3.setText("Password :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 113, 193));
        txtUsuario.setToolTipText("");
        txtUsuario.setBorder(null);
        txtUsuario.setCaretColor(new java.awt.Color(0, 113, 193));
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 240, 30));

        boton.setBackground(new java.awt.Color(29, 29, 29));
        boton.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        boton.setForeground(new java.awt.Color(0, 113, 193));
        boton.setText("Registrarse");
        boton.setBorder(null);
        boton.setContentAreaFilled(false);
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });
        jPanel2.add(boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 130, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 113, 193));
        jSeparator1.setForeground(new java.awt.Color(0, 113, 193));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 130, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 113, 193));
        jSeparator2.setForeground(new java.awt.Color(0, 113, 193));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 240, 10));

        psfPassword.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        psfPassword.setForeground(new java.awt.Color(0, 113, 193));
        psfPassword.setBorder(null);
        psfPassword.setCaretColor(new java.awt.Color(0, 113, 193));
        jPanel2.add(psfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 240, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 113, 193));
        jSeparator3.setForeground(new java.awt.Color(0, 113, 193));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 240, 10));

        btnIniciarSesion.setBackground(new java.awt.Color(0, 113, 193));
        btnIniciarSesion.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 120, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/agregar-usuario (1).png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/contraseña.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 40, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 480, 600));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/img/encuestas.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        FrmRegistrate registrate = new FrmRegistrate();
        registrate.setVisible(true);
    }//GEN-LAST:event_botonActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
         try {
            String username = txtUsuario.getText();
            String password = psfPassword.getText();
            if (username.equals("admin") && password.equals("123")) {
                role = "Administrador";
                userID = Long.parseLong("0");
            } else {
                Login login = controlador.iniciarSesion(username, password);
                userID = login.getDni();
                role = login.getRol();
            }
            MenuPrincipal mainMenu = new MenuPrincipal();
            mainMenu.setVisible(true);
            this.setVisible(false);

        } catch (ConexionException | PasswordIncorrectoException | UsernameIncorrectoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField psfPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
