/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JInternalFrame;
//import sun.tools.java.Constants;

/**
 *
 * @author SEBASTIAN
 */
public class FrmPreguntas extends javax.swing.JFrame {

    /**
     * Creates new form FrmPreguntas
     */
    private JInternalFrame ventanaActual;
    int idSupCategoria;

    public FrmPreguntas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    FrmPreguntas(int idSupCategoria) {
        this.idSupCategoria = idSupCategoria;
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtgSeleccionPregunta = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        RdbEscala = new javax.swing.JRadioButton();
        RdbPreguntaMixta = new javax.swing.JRadioButton();
        RdbSeleccionUnica = new javax.swing.JRadioButton();
        RdbSeleccionMultiple = new javax.swing.JRadioButton();
        RdbRanking = new javax.swing.JRadioButton();
        panelInterno1 = new vistas.PanelInterno();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 113, 193));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 113, 193));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Tipo De Pregunta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai Light", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RdbEscala.setBackground(new java.awt.Color(0, 113, 193));
        BtgSeleccionPregunta.add(RdbEscala);
        RdbEscala.setForeground(new java.awt.Color(255, 255, 255));
        RdbEscala.setText("Escala");
        RdbEscala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RdbEscalaMouseClicked(evt);
            }
        });
        jPanel5.add(RdbEscala, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        RdbPreguntaMixta.setBackground(new java.awt.Color(0, 113, 193));
        BtgSeleccionPregunta.add(RdbPreguntaMixta);
        RdbPreguntaMixta.setForeground(new java.awt.Color(255, 255, 255));
        RdbPreguntaMixta.setText("Pregunta Mixta");
        RdbPreguntaMixta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RdbPreguntaMixtaMouseClicked(evt);
            }
        });
        RdbPreguntaMixta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdbPreguntaMixtaActionPerformed(evt);
            }
        });
        jPanel5.add(RdbPreguntaMixta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        RdbSeleccionUnica.setBackground(new java.awt.Color(0, 113, 193));
        BtgSeleccionPregunta.add(RdbSeleccionUnica);
        RdbSeleccionUnica.setForeground(new java.awt.Color(255, 255, 255));
        RdbSeleccionUnica.setText("Seleccion Única");
        RdbSeleccionUnica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RdbSeleccionUnicaMouseClicked(evt);
            }
        });
        jPanel5.add(RdbSeleccionUnica, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        RdbSeleccionMultiple.setBackground(new java.awt.Color(0, 113, 193));
        BtgSeleccionPregunta.add(RdbSeleccionMultiple);
        RdbSeleccionMultiple.setForeground(new java.awt.Color(255, 255, 255));
        RdbSeleccionMultiple.setText("Seleccion Múltiple");
        RdbSeleccionMultiple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RdbSeleccionMultipleMouseClicked(evt);
            }
        });
        RdbSeleccionMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdbSeleccionMultipleActionPerformed(evt);
            }
        });
        jPanel5.add(RdbSeleccionMultiple, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        RdbRanking.setBackground(new java.awt.Color(0, 113, 193));
        BtgSeleccionPregunta.add(RdbRanking);
        RdbRanking.setForeground(new java.awt.Color(255, 255, 255));
        RdbRanking.setText("Ranking");
        RdbRanking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RdbRankingMouseClicked(evt);
            }
        });
        jPanel5.add(RdbRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 570, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 670, 120));

        panelInterno1.setForeground(new java.awt.Color(255, 255, 255));
        panelInterno1.setMaximumSize(new java.awt.Dimension(660, 450));
        panelInterno1.setMinimumSize(new java.awt.Dimension(660, 450));
        panelInterno1.setName(""); // NOI18N
        getContentPane().add(panelInterno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 670, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RdbEscalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdbEscalaMouseClicked
        if (ventanaActual == null) {
            ventanaActual = new FrmEleccionEscala(idSupCategoria);
            panelInterno1.add(ventanaActual);
        } else {
            panelInterno1.remove(ventanaActual);
            panelInterno1.repaint();
            ventanaActual = new FrmEleccionEscala(idSupCategoria);
            panelInterno1.add(ventanaActual);
        }
    }//GEN-LAST:event_RdbEscalaMouseClicked

    private void RdbPreguntaMixtaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdbPreguntaMixtaMouseClicked
        if (ventanaActual == null) {
            ventanaActual = new FrmPreguntaMixta(idSupCategoria);
            panelInterno1.add(ventanaActual);
        } else {
            panelInterno1.remove(ventanaActual);
            panelInterno1.repaint();
            ventanaActual = new FrmPreguntaMixta(idSupCategoria);
            panelInterno1.add(ventanaActual);
        }
    }//GEN-LAST:event_RdbPreguntaMixtaMouseClicked

    private void RdbPreguntaMixtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdbPreguntaMixtaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdbPreguntaMixtaActionPerformed

    private void RdbSeleccionUnicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdbSeleccionUnicaMouseClicked
        if (ventanaActual == null) {
            ventanaActual = new FrmEleccionUnica(idSupCategoria);
            panelInterno1.add(ventanaActual);
        } else {
            panelInterno1.remove(ventanaActual);
            panelInterno1.repaint();
            ventanaActual = new FrmEleccionUnica(idSupCategoria);
            panelInterno1.add(ventanaActual);
        }
    }//GEN-LAST:event_RdbSeleccionUnicaMouseClicked

    private void RdbSeleccionMultipleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdbSeleccionMultipleMouseClicked
        if (ventanaActual == null) {
            ventanaActual = new FrmEleccionMultiple(idSupCategoria);
            panelInterno1.add(ventanaActual);
        } else {
            panelInterno1.remove(ventanaActual);
            panelInterno1.repaint();
            ventanaActual = new FrmEleccionMultiple(idSupCategoria);
            panelInterno1.add(ventanaActual);
        }
    }//GEN-LAST:event_RdbSeleccionMultipleMouseClicked

    private void RdbSeleccionMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdbSeleccionMultipleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdbSeleccionMultipleActionPerformed

    private void RdbRankingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdbRankingMouseClicked
        if (ventanaActual == null) {
            ventanaActual = new FrmRanking(idSupCategoria);
            panelInterno1.add(ventanaActual);
        } else {
            panelInterno1.remove(ventanaActual);
            panelInterno1.repaint();
            ventanaActual = new FrmRanking(idSupCategoria);
            panelInterno1.add(ventanaActual);
        }
    }//GEN-LAST:event_RdbRankingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtgSeleccionPregunta;
    private javax.swing.JRadioButton RdbEscala;
    private javax.swing.JRadioButton RdbPreguntaMixta;
    private javax.swing.JRadioButton RdbRanking;
    private javax.swing.JRadioButton RdbSeleccionMultiple;
    private javax.swing.JRadioButton RdbSeleccionUnica;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private vistas.PanelInterno panelInterno1;
    // End of variables declaration//GEN-END:variables
}
